### ISSUE TITLE
Cypher Exports breaks

### ISSUE THREAD

**Issue by RyanSnodgrass** [ndoit/fenrir#624]
Clicked on "Do Cypher Exports" in data-test and got this stack trace in the log
```
RuntimeError Database not found: EDW Staging
/apps/fenrir/app/models/sql/dataset_server.rb:23:in `connection'
/apps/fenrir/app/jobs/cypher_to_sql_job.rb:28:in `init_db'
/apps/fenrir/app/jobs/cypher_to_sql_job.rb:7:in `perform'
/usr/local/rvm/gems/ruby-2.3.4/gems/sucker_punch-2.0.2/lib/sucker_punch/job.rb:54:in `__run_perform'
/usr/local/rvm/gems/ruby-2.3.4/gems/sucker_punch-2.0.2/lib/sucker_punch/job.rb:36:in `block in perform_async'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/usr/local/rvm/gems/ruby-2.3.4/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by RyanSnodgrass** [comment]
Fixed by #634
